#all the other yml file will inherit from this one
#generic configuration
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    config:
      override.system-properties: false #default is true. Don't want to overwrite any properties

management:
  tracing:
    sampling:
      probability: 1.0 #range from 0 to 1 that a trace will be sampled