spring:
  data:
    mongodb:
      username: scott
      password: kang
      host: localhost
      port: 27018 #defined in the docker compose yml file
      database: customer
      authentication-database: admin
server:
  port: 8090 #technically if multiple instances this is not necessary
